name: MOTUS

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - name: Test
        uses: actions/checkout@v1
      - name: Build and Test
        run:  xcodebuild test -project MOTUS.xcodeproj -scheme MOTUS -enableCodeCoverage YES build test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1.2.1